### ISSUE TITLE
[Feature request] detect when VM is running in Shielded mode

### ISSUE THREAD

**Issue by KitCat36** [0xf005ba11/vmplex-ws#21]
When VM is running in Shielded mode, basic session mode can't be used. the default Hyper-V UI shows this:

![image](https://user-images.githubusercontent.com/72892766/198291582-e260ce3e-7621-430e-b414-1ebee84b2dec.png)

but VMplex-ws shows this:

![image](https://user-images.githubusercontent.com/72892766/198291729-4fcd74fd-4001-4279-8735-ad5c5d84c595.png)

no messages.

so, I suggest disabling basic session mode entirely for Shielded VMs and only allow Enhanced session mode to be used. there can be a pop-up message as well informing the user about this.

**Comment by jxy-s** [comment]
@0xf005ba11 identified some undesirable behavior for shielded VMs, decorated as a bug, assigned to them for triage and resolution.

**Comment by 0xf005ba11** [comment]
Proposed fix in https://github.com/0xf005ba11/vmplex-ws/pull/22
