### ISSUE TITLE
[Feature Request] add vmplex to the Winget repository

### ISSUE THREAD

**Issue by lulMeow** [0xf005ba11/vmplex-ws#28]
Please add vmplex-ws to the Winget repository for easy installation and updating.
Ideally i'd rather install and update it through Windows store but not sure if you need to pay to publish in there and if portable programs are supported.
I think doing either of these will make things easier for users.

Winget supports portable software:
https://learn.microsoft.com/en-us/windows/package-manager/winget/

by installation, I mean copying the executable to a local directory and add its icon to the start menu.

**Comment by jxy-s** [comment]
I would love to have winget support in the future. 👍

**Comment by MouriNaruto** [comment]
@jxy-s

In my opinion, I think maybe vmplex can be submitted to the Microsoft Store. It achieve get vmplex via both winget and msstore.

Note: I am the author of [NanaGet](https://github.com/M2Team/NanaBox), a third-party lightweight XAML-based out-of-box-experience oriented Hyper-V client based on Host Compute System API, Remote Desktop ActiveX control and XAML Islands. I had submitted NanaBox to [Microsoft Store](https://www.microsoft.com/store/apps/9NJXJSCB2JK0) successfully. So, I think VMPlex Workstation also can achieve that.

Kenji Mouri

**Comment by jxy-s** [comment]
Decided to go directly with winget instead of the store. I think that's a better workflow for the people consuming this type of tool. The request is in, CI has passed, we're waiting on moderator approval 🤞 : https://github.com/microsoft/winget-pkgs/pull/102646

**Comment by jxy-s** [comment]
This is complete 🎉 : https://github.com/microsoft/winget-pkgs/pull/105827

`winget install vmplex`
